language: node_js
node_js:
- '4.0'

script:
- npm run-script travis

notifications:
  slack:
    secure: W/D3AEszCIvbkAISABUFdz5wlS5Fo+dh3DLoUd0v1fsm+jKDNN+7wJ1kIctosru+bail2Vzyr1oiHLjF8+IbitRGZ1VT8/BTpvynrp2haEUlshYsYBAVts5Y6AA/3V6WFl6FzJaHPDLsrox8OQ3Xztubhz4ybWPfk69KQvx0hYA=
