language: node_js
node_js:
- '4'
- '5'
notifications:
  slack:
    rooms:
      secure: a/EtGegOdAisaPmMPWLhS7c/ujAxj08UO5YU1pb98NgMc+ED0UW1xeHrsFFT8oIv9NV9l/mEo+h9N/rH0ZiS/Xu0S+0VIU/sBszJRly1Gql8b6PWg+9O+n1tG4koljSbXfDWYF/ZVUcAkFjoG8Y955+IkQZ4UcSi5pSF/pxt4+WHkzMa3OjbTAlxR4N8ObCI//mwjHfViLyI0mwdE8fHVhXik+RRG6qg1luCFCBVFn6SQfiGLW0rEOywZ3sGQhfS1IKMt8gWX9ng2S8IQry5N4YaRcTyjKEuDgMWT8nzcbv/qxtTvUloN9Kd8JYW/wctGSEQZiGUigLysEn/sOA2i2s60KFCYStIDYJ8ZfAa2jZ4xffNFQyyFTOUozcg+ZEvF7+/LFaEaAWhZ4lJTTFegZhEGdeFDMBi5Ft2YZ9IQrLtK7rg7v4vBXK0hgAeW3CWuKqyUQMd1v8Pd9NKlhEqdP0sbzr8bRDZr0Fc1tQ1in/4fryo710dUWVBzlxRcfprJ2SSFJs7yx1+JtKNHP3wRawsXBCuPXtuYvr2Hg8E3svsXfflqLpchLhxwpBc5Pjr6NGNRRSr42b3yzTMwkHeoQAynEwB+91z25H5F1m689wF3/ErIeuCRHKcQ4ZNprTWt/4pqvl0YFaAt7Mcaxpo9jm0VuP4AEttsKxV12IK7h8=
